//! Vietnamese compound word/phrase dictionary (TuDienTuGhep).
//!
//! Provides O(log n) lookup for ~68K Vietnamese compound phrases using binary search
//! on a sorted UTF-8 binary blob generated at build time from data/TuDienTuGhep.txt.
//!
//! ## Binary format
//! - Header: u32 entry count (little-endian)
//! - Offset table: entry_count × u32 offsets from start of data section (LE)
//! - Data section: entries, each [u16 byte_len][UTF-8 bytes]
//!
//! ## Usage
//! ```
//! use goxviet_core::infrastructure::data::viet_compound_data::is_vietnamese_compound;
//!
//! assert!(is_vietnamese_compound("ánh sáng"));
//! assert!(!is_vietnamese_compound("hello world"));
//! ```

use std::cmp::Ordering;

// Binary blob generated by build.rs from data/TuDienTuGhep.txt
static COMPOUND_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/viet_compound.bin"));

/// Parsed metadata from the binary blob header.
struct CompoundIndex {
    count: u32,
    /// Byte offset in COMPOUND_DATA where the offset table starts (after count u32)
    offset_table_start: usize,
    /// Byte offset in COMPOUND_DATA where entry data starts (after offset table)
    data_start: usize,
}

impl CompoundIndex {
    fn load() -> Self {
        if COMPOUND_DATA.len() < 4 {
            return CompoundIndex {
                count: 0,
                offset_table_start: 4,
                data_start: 4,
            };
        }
        let count = u32::from_le_bytes([
            COMPOUND_DATA[0],
            COMPOUND_DATA[1],
            COMPOUND_DATA[2],
            COMPOUND_DATA[3],
        ]);
        let offset_table_start = 4usize;
        let data_start = 4 + (count as usize * 4);
        CompoundIndex {
            count,
            offset_table_start,
            data_start,
        }
    }

    /// Get entry at index i as a UTF-8 str.
    fn get_entry<'a>(&self, i: u32) -> &'a str {
        let off_pos = self.offset_table_start + (i as usize * 4);
        let offset = u32::from_le_bytes([
            COMPOUND_DATA[off_pos],
            COMPOUND_DATA[off_pos + 1],
            COMPOUND_DATA[off_pos + 2],
            COMPOUND_DATA[off_pos + 3],
        ]) as usize;

        let entry_pos = self.data_start + offset;
        let len = u16::from_le_bytes([COMPOUND_DATA[entry_pos], COMPOUND_DATA[entry_pos + 1]])
            as usize;
        let bytes = &COMPOUND_DATA[entry_pos + 2..entry_pos + 2 + len];
        // Safety: build.rs wrote valid UTF-8 from TuDienTuGhep.txt
        unsafe { std::str::from_utf8_unchecked(bytes) }
    }
}

/// Check if `text` is a valid Vietnamese compound word or phrase.
///
/// Performs binary search on the sorted compound dictionary (~68K entries).
/// Complexity: O(log n) with ~17 comparisons for 68K entries.
pub fn is_vietnamese_compound(text: &str) -> bool {
    let idx = CompoundIndex::load();
    if idx.count == 0 {
        return false;
    }

    let mut left: u32 = 0;
    let mut right: u32 = idx.count;

    while left < right {
        let mid = left + (right - left) / 2;
        let entry = idx.get_entry(mid);
        match entry.cmp(text) {
            Ordering::Equal => return true,
            Ordering::Less => left = mid + 1,
            Ordering::Greater => right = mid,
        }
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_compounds_present() {
        // Sample entries from TuDienTuGhep.txt (first few lines)
        assert!(is_vietnamese_compound("á châu"), "'á châu' should be in compound dict");
        assert!(is_vietnamese_compound("á đông"), "'á đông' should be in compound dict");
        assert!(is_vietnamese_compound("á hậu"), "'á hậu' should be in compound dict");
    }

    #[test]
    fn test_english_phrases_absent() {
        assert!(!is_vietnamese_compound("hello world"));
        assert!(!is_vietnamese_compound("restore windows"));
        assert!(!is_vietnamese_compound("array index"));
    }

    #[test]
    fn test_empty_string() {
        assert!(!is_vietnamese_compound(""));
    }

    #[test]
    fn test_binary_size_reasonable() {
        // The 1MB TuDienTuGhep.txt with offset index fits in ~1.5MB binary.
        // Note: plan estimated 250KB, but that's unrealistic for 68K UTF-8 entries.
        // Real constraint: binary must be smaller than the raw .txt + some index overhead.
        let size_kb = COMPOUND_DATA.len() as f64 / 1024.0;
        println!("viet_compound.bin size: {:.1}KB", size_kb);
        assert!(
            COMPOUND_DATA.len() < 2 * 1024 * 1024,
            "viet_compound.bin is {:.0}KB, should be < 2MB",
            size_kb
        );
    }

    #[test]
    fn test_entry_count() {
        let idx = CompoundIndex::load();
        println!("TuDienTuGhep: {} entries", idx.count);
        assert!(idx.count > 60_000, "Expected 60K+ compound entries, got {}", idx.count);
        assert!(idx.count < 80_000, "Expected < 80K compound entries, got {}", idx.count);
    }
}
