//! Double-consonant English word dictionary.
//!
//! Contains English words with Telex tone-marker double consonants (ff/ss/rr/xx/jj).
//! Used at SPACE boundary to correct triple-tone typos, e.g. "assset" → "asset".
//!
//! Generated at build time from `src/data/double_consonant_words.txt`.

// Include the phf::Set generated by build.rs at module level
include!(concat!(env!("OUT_DIR"), "/double_consonant_words.rs"));

/// Returns true if `word` is a known English word containing a tone-marker double consonant.
#[inline]
pub fn is_double_consonant_word(word: &str) -> bool {
    DOUBLE_CONSONANT_WORDS.contains(word)
}
