//! English word dictionary for Telex auto-restore disambiguation.
//!
//! Provides O(1) lookup for common English words using a perfect hash
//! function (phf) generated at build time from data/EnglishWords.txt.
//!
//! ## Usage
//! ```
//! use goxviet_core::data::english_words::is_english_word;
//!
//! assert!(is_english_word("book"));
//! assert!(is_english_word("window"));
//! assert!(!is_english_word("không"));
//! ```

// Include the phf::Set generated by build.rs
include!(concat!(env!("OUT_DIR"), "/english_words.rs"));

/// Check if `s` is a known English word.
///
/// The lookup table contains ~11K common English words from EnglishWords.txt.
/// Complexity: O(1) via perfect hash function.
/// Input must be lowercase ASCII.
#[inline]
pub fn is_english_word(s: &str) -> bool {
    ENGLISH_WORDS.contains(s)
}
