//! Vietnamese single-syllable dictionary (TuDien).
//!
//! Provides O(1) lookup for valid Vietnamese syllables using a perfect hash
//! function (phf) generated at build time from data/TuDien.txt (~7K entries).
//!
//! ## Usage
//! ```
//! use goxviet_core::data::viet_syllables::is_valid_vietnamese_syllable;
//!
//! assert!(is_valid_vietnamese_syllable("anh"));
//! assert!(is_valid_vietnamese_syllable("không"));
//! assert!(!is_valid_vietnamese_syllable("array"));
//! ```

// Include the phf::Set generated by build.rs
include!(concat!(env!("OUT_DIR"), "/viet_syllables.rs"));

/// Check if `s` is a valid Vietnamese single syllable.
///
/// The lookup table contains all ~7,000 entries from TuDien.txt (Unicode NFC).
/// Complexity: O(1) via perfect hash function (fast path); O(n) allocation only
/// when the input contains uppercase letters (e.g. sentence-start capitalization).
#[inline]
pub fn is_valid_vietnamese_syllable(s: &str) -> bool {
    // Fast path: exact match (the common case — input is already lowercase).
    if VIET_SYLLABLES.contains(s) {
        return true;
    }
    // Normalize capitalized input (e.g. "Trường" → "trường").
    // Required because TuDien.txt stores only lowercase entries, but the buffer
    // preserves the caps flag, producing uppercase-first strings for words typed
    // at sentence start or as proper nouns.
    let lower = s.to_lowercase();
    if lower == s {
        return false; // Already lowercase — no point re-checking.
    }
    VIET_SYLLABLES.contains(lower.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_syllables_present() {
        // Basic vowels with tones
        assert!(is_valid_vietnamese_syllable("a"), "'a' should be valid");
        assert!(is_valid_vietnamese_syllable("á"), "'á' should be valid");
        assert!(is_valid_vietnamese_syllable("à"), "'à' should be valid");

        // Common Vietnamese syllables
        assert!(is_valid_vietnamese_syllable("anh"), "'anh' should be valid");
        assert!(
            is_valid_vietnamese_syllable("không"),
            "'không' should be valid"
        );
        assert!(
            is_valid_vietnamese_syllable("bình"),
            "'bình' should be valid"
        );
        assert!(
            is_valid_vietnamese_syllable("đường"),
            "'đường' should be valid"
        );
        assert!(
            is_valid_vietnamese_syllable("người"),
            "'người' should be valid"
        );
        assert!(is_valid_vietnamese_syllable("ăn"), "'ăn' should be valid");
        assert!(
            is_valid_vietnamese_syllable("uống"),
            "'uống' should be valid"
        );
    }

    #[test]
    fn test_english_words_absent() {
        assert!(
            !is_valid_vietnamese_syllable("array"),
            "'array' should NOT be valid Vietnamese"
        );
        assert!(
            !is_valid_vietnamese_syllable("windows"),
            "'windows' should NOT be valid Vietnamese"
        );
        assert!(
            !is_valid_vietnamese_syllable("restore"),
            "'restore' should NOT be valid Vietnamese"
        );
        assert!(
            !is_valid_vietnamese_syllable("print"),
            "'print' should NOT be valid Vietnamese"
        );
        assert!(
            !is_valid_vietnamese_syllable("enter"),
            "'enter' should NOT be valid Vietnamese"
        );
    }

    #[test]
    fn test_capitalized_vietnamese_syllables() {
        // Capitalized forms (sentence-start / proper nouns) must also be recognized.
        assert!(is_valid_vietnamese_syllable("Trường"), "'Trường' (capitalized) should be valid");
        assert!(is_valid_vietnamese_syllable("Anh"), "'Anh' should be valid");
        assert!(is_valid_vietnamese_syllable("Không"), "'Không' should be valid");
        assert!(is_valid_vietnamese_syllable("Bình"), "'Bình' should be valid");
        assert!(is_valid_vietnamese_syllable("Đường"), "'Đường' should be valid");
    }

    #[test]
    fn test_empty_string() {
        assert!(
            !is_valid_vietnamese_syllable(""),
            "Empty string should not be valid"
        );
    }

    #[test]
    fn test_lookup_all_tu_dien_entries() {
        // Verify the set was built correctly — all TuDien entries must be present
        let tu_dien = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/data/TuDien.txt"));
        let mut missing = 0usize;
        for line in tu_dien.lines() {
            let word = line.trim();
            if !word.is_empty() && !is_valid_vietnamese_syllable(word) {
                eprintln!("MISSING from VIET_SYLLABLES: '{}'", word);
                missing += 1;
            }
        }
        assert_eq!(
            missing, 0,
            "{} entries from TuDien.txt not found in VIET_SYLLABLES",
            missing
        );
    }
}
